### ISSUE TITLE
Fresh app fails running or prebuild for ios

### ISSUE THREAD

**Issue by mwarger** [danstepanov/create-expo-stack#180]
## Expected Behavior

The app should run after creation

## Current Behavior
⚠️  Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: Unable to find a specification for `ExpoModulesCore` depended upon by `EXFont`

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
## Possible Solution

Based on some googling, could be possibly related to https://github.com/danstepanov/create-expo-stack/issues/176

## Steps to Reproduce
Run `npx create-expo-stack@latest --no-git` and choose options resulting in `npx create-expo-stack mobile --expo-router --tabs --tamagui --no-git `
cd mobile
npx expo prebuild

**Comment by danstepanov** [comment]
Which version of the cli are you running?

**Comment by finnbayer** [comment]
from what I tested it fails on the new version 2.3.15 but works on 2.3.14. Seems like the override fixed one issue but opened up another...
I can't get to the bottom of it :/

**Comment by mwarger** [comment]
> Which version of the cli are you running?

@danstepanov What cli do you mean?

**Comment by mwarger** [comment]
@finnbayer @danstepanov FYI - when running `create-expo-stack@2.3.14` I do not see issues.

**Comment by danstepanov** [comment]
I'm going to add some conditional hacky shit to get this to work for now until we are aware of a more permanent fix

**Comment by mwarger** [comment]
@danstepanov @finnbayer My mistake, on a second look with this, on the previous version, I end up with the same issue as was reported previously (#176) when running the ios app.  Sorry for the confusion here.
```
ERROR  TypeError: 0, _expoModulesCore.requireOptionalNativeModule is not a function (it is undefined), js engine: hermes
```

**Comment by danstepanov** [comment]
@mwarger are you in the discord? Might be better to further debug there for more instant comms. https://createexpostack.com/discord

**Comment by danstepanov** [comment]
This issue pertains specifically to trying to use the dev client. We are in the process of implementing #177 which will resolve this entirely. In the meantime, I'll play around and see if I can get a hacky workaround.
